version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3

jobs:
  test:
    docker:
      - image: cimg/clojure:1.11.1-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run: npm ci
      - run: clojure -X:test
      - run: npm run test:cljs:node
      - run: npm run test:cljs:browser

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
