version: 2.1
jobs:
  test:
    docker:
      - image: cimg/clojure:1.11.1-node
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y google-chrome-stable
      - run: npm install
      - run: clojure -X:test
      - run: npm run test:cljs:node
      - run: npm run test:cljs:browser

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
